import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Projects from '../components/Projects/Projects'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Steve Braco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Projects />
    </div>
  )
}
